events {}

http {
    resolver 127.0.0.11 ipv6=off valid=5s;

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        location / {
            set $upstream_lb lb;
            proxy_pass https://$upstream_lb:8443;

            proxy_ssl_server_name on;
            proxy_ssl_name $upstream_lb;
            proxy_ssl_verify off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
